--- 
  - name: install and start file server
    yum: 
      name: 
        - "{{ ansible_local.custom.packages.smb_package }}"
        - "{{ ansible_local.custom.packages.ftp_package }}"
      state: latest

  - name: start samba server
    service:
      name: "{{ ansible_local.custom.packages.smb_package }}"
      enabled: true
      state: started 

  - name: start ftp server
    service:
      name: "{{ ansible_local.custom.packages.smb_package }}"
      enabled: true
      state: started 
...
