---
# copy shell scripts to remote host
- name: copy
  hosts: all
  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: /home/localusr/ansible/test.sh
      dest: /var/test.sh
      owner: 1001
      group: 100
      mode: '0700'
