---
- yum:
    name: "{{ fw_package }}"
    state: latest

- service:
    name: "{{ fw_package }}"
    state: started

- firewalld:
    service: "{{ item }}"
    immediate: true
    permanent: true
    state: enabled
  with_items:
    - http
    - https
